import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { getServerSession } from "next-auth";
import SessionProvider from "@/components/sessionProvider";
import { Toaster } from "@/components/ui/toaster";
import { Toaster as Sonner } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>{children}</SessionProvider>
        <Toaster />
        <Sonner richColors />
      </body>
    </html>
  );
}
